=== Create a search page

:idprefix:
:idseparator: -

The fastest way to create a new search page in a feature module is to use the OneCX generator.
include::partial$generator-check.adoc[]

******
To run the generator, execute the following command: 
----
nx generate <namespaceOfTheGenerator>/nx-plugin:search <feature>
----

include::partial$generator-namespace-item.adoc[]

* _<feature>_: see xref:./glossary.adoc#feature[here].

TIP: Next, the CLI will ask you whether you want to customize names for the generation.
When answering yes, the next few questions will ask you about names for the API.
This can be useful if you want to adapt to a legacy API.
When modifying names, assure that you use the same custom names for all generated components of the feature (search, details, create-update, delete) for the resource name, and the api service name as these are shared.

******

After running the generator, the following actions must be taken: 

[start=1]
. xref:./search/configure-search-criteria.adoc[Configure search criteria]
. xref:./search/configure-search-results.adoc[Configure search results]
. xref:./search/configure-result-diagram.adoc[Configure result diagram]
. xref:./search/update-header-actions.adoc[Update Header Actions]
. xref:./search/update-permissions.adoc[Update permissions]
. xref:./search/further-actions.adoc[Check for further actions]
. xref:./search/commit-changes.adoc[Commit the changes]

*Extension Marker in Search Page Spec File*
******
We use the marker: 
----
<<SPEC-EXTENSIONS-MARKER-!!!-DO-NOT-REMOVE-!!!>>
----
This marker is used as a placeholder for future extensions by newly generated components. Do not remove the marker from the code, as doing so will prevent these future generated functions and tests from being added to the Search Page Spec File.
