=== Configure the search results. 

:idprefix:
:idseparator: -

:data_table_column_properties_cookbook_url: xref:latest@guides:angular:ngrx/cookbook/search-results/data-table-column.adoc

To configure the search results, the following actions must be taken. 

[#action-5]
==== ACTION S5: Add additional properties
Here you can add additional properties which you need for your `+<SearchFeatureResponse>+`.

* The `+<FeatureName>+` data object structure in the BFF yaml can be adapted. 
** If you have chosen a custom DataObjectName in the generation, the schema entry will be named accordingly.
** All the data that should be displayed in the results must be in that data structure either on top-level or in sub data structures. 
** The data should be as minimal as possible to not create too much load to the backend and the DB. 

_Adapt in File:_ `+<feature>-bff.yaml+`

.Example:
[source, yml]
----
  <Feature>:
        type: object
        required:
          - 'modificationCount'
          - 'id'
        properties:
          modificationCount:
            type: integer
            format: int32
          id:
            type: integer
            format: int64
          exampleProperty:
            type: string
----

IMPORTANT: After updating the OpenAPI specification, execute the command *npm run apigen* to generate the corresponding TypeScript code.

include::partial$remove-action.adoc[]

[#action-6]
==== ACTION S6: Define search results columns
The column mappings must be defined. 

_Adapt in File:_ `+<feature>-search.columns.ts+`
.Example:
[subs=+macros]
[source, javascript]
----
  export const FeaturePropertySearchColumns: DataTableColumn[] = [
        {
        columnType: ColumnType.STRING,
        id: 'columnId',
        nameKey: 'FEATURE_PROPERTY_SEARCH.RESULTS.COLUMN_ID',
        filterable: true,
        sortable: true,
        predefinedGroupKeys: [
          'FEATURE_PROPERTY_SEARCH.PREDEFINED_GROUP.DEFAULT',
          'FEATURE_PROPERTY_SEARCH.PREDEFINED_GROUP.EXTENDED',
          'FEATURE_PROPERTY_SEARCH.PREDEFINED_GROUP.FULL',
        ],
      },
  ]
----

Refer to the {data_table_column_properties_cookbook_url}[DataTableColumn properties overview cookbook] for more information.

include::partial$remove-action.adoc[]

[#action-7]
==== ACTION S7: Mapping of the items and respective translations

Here you can create a mapping of the items and their corresponding translation strings for columns with type `TRANSLATION_KEY` to translate the values in the talbe rows respective to the column.

_Adapt in File:_ <feature>-search.selectors.ts
.Example:
[source, javascript]
----
  export const selectResults = createSelector(
    ExampleFeaturePropertySearchSelectors.selectResults,
    (results): RowListGridData[] => {
      return results.map((item) => ({      
        imagePath: '',
        ...item,
        columnId1: item.columnId1
          ? `EXAMPLE_FEATUTRE_PROPERTY_SEARCH.RESULTS.COLUMNID1.${item.columnId1}`
          : '',
      }));
    }
  );
----

include::partial$remove-action.adoc[]

[#action-8]
==== ACTION S8: Add translation
// TODO: reference to cookbook e.g.: angular/cookbook/translations

_Adapt in File:_ `+de.json+` / `+en.json+`

Please ensure that all column headers and the values in columns with the type `TRANSLATION_KEY` have the necessary translations added.

include::partial$remove-action.adoc[]
