=== Configure the search criteria and parameters

:idprefix:
:idseparator: -

:adding_search_criteria_general_cookbook_url: xref:latest@guides:angular:ngrx/cookbook/adding-search-criteria/general.adoc
:adding_search_criteria_general_parameters_cookbook_url: xref:latest@guides:angular:ngrx/cookbook/adding-search-criteria/general.adoc#parameters
:adding_search_criteria_general_html_url: xref:latest@guides:angular:ngrx/cookbook/adding-search-criteria/general.adoc#html
:adding_search_criteria_general_html_examples_url: xref:latest@guides:angular:ngrx/cookbook/adding-search-criteria/general.adoc#examples-for-different-input-fields
:adding_translations_cookbook_url: xref:latest@guides:angular/pages/cookbook/translations.adoc

[#action-1]
==== ACTION S1: Add additional properties

You should have a `+Search<Feature>Request+` defined in the OpenAPI specification, which should be in file `+<feature>-bff.yaml+`. 
Where `feature` is the name of your entity. By modifying `+<feature>-bff.yaml+` file you can add additional parameters to your search request.
All the data that should be used in the search request must be in that OpenAPI data structure either on top-level or in sub data structures.

Please refer to the {adding_search_criteria_general_cookbook_url}["Adding search criteria" cookbook] for more information.

After updating the OpenAPI specification, execute the command *npm run apigen* to generate the corresponding TypeScript code.

_Remove "ACTION S1" comment after working on this task._

[#action-2]
==== ACTION S2: Define the members
In order to use search criteria, which you just defined in "ACTION S1", you need to modify the file, containing typescript representation of the search parameters. 
Such file should be called `+<feature>-search.parameters.ts+`. There you need to define the members for your `+<Feature>SearchCriteriasSchema+`. Where `feature` is again the name of your entity.

While defining search parameters note that:

* keys *need* to match the keys from your OpenAPIs SearchCriteria Object
* always start with `+z.string()+`
* when required, you can use `+.transform()+` to extend the validation
* dates are always mapped to strings (as JSON does not know DateTime)

Refer to the {adding_search_criteria_general_parameters_cookbook_url}["Parameters" section of "Adding search criteria" cookbook].

_Remove "ACTION S2" comment after working on this task._

[#action-3]
==== ACTION S3: Specify desired search criterias
In order to make the search criteria visible to the end user, you need to modify HTML view, located in the file called `+<feature>-search.component.html+`.
Please specify your desired search criterias by adding HTML input fields. You can add different types of input fields, like `+Text+`, `+Calendar+`, `+Dropdown+`,
`+MultiSelect+` or `+AutoComplete+`.

Please refer to the {adding_search_criteria_general_html_url}["HTML" section of "Adding search criteria" cookbook].

_Remove "ACTION S3" comment after working on this task._


[#action-4]
==== ACTION S4: Add translations
The translations in German and English languages should be defined in corresponding files: `+de.json+` / `+en.json+`

Please ensure that all input field labels have the necessary translations added.
Refer to the {adding_translations_cookbook_url}[cookbook describing translations].

_Remove "ACTION S4" comment after working on this task._

---
Now you can continue with the next section xref:getting_started/search/configure-search-results.adoc[Configure search results]
