= Configure the search criteria and parameters

:idprefix:
:idseparator: -

[#action-1]
== ACTION S1: Add additional properties

The `+Search<FeatureName>Request+` data structure in the BFF yaml must be adapted. 

All the data that should be used in the request must be in that data structure either on top-level or in sub data structures.

_Adapt in File:_ `+<feature>-bff.yaml+`

.Example:
[source, yml]
----
SearchExampleFeatureRequest:
      type: object
      properties:
        pageNumber: 
          type: integer
          format: int32
          default: 0
          description: 'The number of the page.'          
        pageSize:
          type: integer
          format: int32
          default: 100
          maximum: 1000
          description: 'The size of the page.'      
        id:
          type: string
        exampleProperty:
          type: string
----

Please refer to the following cookbook for more information:
https://onecx.github.io/docs/guides/current/angular/ngrx/cookbook/addingSearchCriteria/general.html

IMPORTANT: After updating the OpenAPI specification, execute the command *npm run apigen* to generate the corresponding TypeScript code.

include::partial$remove-action.adoc[]

[#action-2]
== ACTION S2: Define the members
Please define the members for your `+<%= featurePropertyName %>SearchCriteriasSchema+`

Adapt search parameters:

* keys *need* to match the keys from your OpenAPIs SearchCriteria Object
* always start with `+z.string()+`
* when required, you can use `+.transform()+` to extend the validation
* dates are always mapped to strings (as JSON does not know DateTime)

_Adapt in File:_ `+<feature>-search.parameters.ts+`

.Example:
[source, javascript]
----
    exampleString: z.string().optional(),
    exampleNumber: z
        .string()
        .transform((v) => (v ? Number(v) : undefined))
        .optional(),
----

Refer to the following cookbook for more types: https://onecx.github.io/docs/guides/current/angular/ngrx/cookbook/addingSearchCriteria/general.html#_parameters

include::partial$remove-action.adoc[]

[#action-3]
== ACTION S3: Specify desired search criterias
Please specify your desired search criterias by adding input fields.

_Adapt in File:_ `+<feature>-search.component.html+`

.Example text input field:
[subs=+macros]
[source, html]
----
  <form [formGroup]="criteriaGroup">
      <div class="grid mt-0 p-fluid">
        <div class="col-12 md:col-3">
          <span class="p-float-label">
            <input
              id="id"
              pInputText
              type="text"
              formControlName="id"
              class="p-inputtext p-component"
            />
            <label for="id">{{
              'EXAMPLE_FEATURE_SEARCH.CRITERIA.ID' | translate
              }}</label>
          </span>
        </div>
      </div>
  </form>    
----

Please refer to the following cookbook for more information:
https://onecx.github.io/docs/guides/current/angular/ngrx/cookbook/addingSearchCriteria/general.html#_html

[#examples-for-different-input-fields]
=== Examples for different input fields
Depending on what kind of input fields you want to add, the implementation differs.

Refer to the following cookbook:
https://onecx.github.io/docs/guides/current/angular/ngrx/cookbook/addingSearchCriteria/general.html#_examples_for_different_input_fields


== ACTION S4: Add translations
_Adapt in File:_  `+de.json+` / `+en.json+`

* Please add the missing translations
// TODO: Specify for what the translation will be added
// TODO: reference to cookbook e.g.: angular/cookbook/translations

---
Now you can continue with the next section xref:getting_started/search/configureSearchResults.adoc[Configure search results]