= Configure the search results. 
To configure the search results, the following actions must be taken. 

[#action-5]
== ACTION S5: Add additional properties
Here you can add additional properties which you need for your `+<SearchFeatureResponse>+`.

* The `+<FeatureName>+` data object structure in the BFF yaml can be adapted. 
** If you have chosen a custom DataObjectName in the generation, the schema entry will be named accordingly.
** All the data that should be displayed in the results must be in that data structure either on top-level or in sub data structures. 
** The data should be as minimal as possible to not create too much load to the backend and the DB. 

_Adapt in File:_ `+<feature>-bff.yaml+`

.Example:
[source, yml]
----
  <Feature>:
        type: object
        required:
          - 'modificationCount'
          - 'id'
        properties:
          modificationCount:
            type: integer
            format: int32
          id:
            type: integer
            format: int64
          exampleProperty:
            type: string
----

IMPORTANT: After updating the OpenAPI specification, execute the command *npm run apigen* to generate the corresponding TypeScript code.

include::partial$remove-action.adoc[]

[#action-6]
== ACTION S6: Define search results columns
The column mappings must be defined. 

_Adapt in File:_ `+<feature>-search.columns.ts+`
.Example:
[subs=+macros]
[source, javascript]
----
  export const ExampleFeaturePropertySearchColumns: DataTableColumn[] = [
        {
        columnType: ColumnType.STRING,
        id: 'columnId',
        nameKey: 'EXAMPLE_FEATUTRE_PROPERTY',
        filterable: true,
        sortable: true,
        predefinedGroupKeys: [
          'EXAMPLE_FEATUTRE_PROPERTY_SEARCH.PREDEFINED_GROUP.DEFAULT',
          'EXAMPLE_FEATUTRE_PROPERTY_SEARCH.PREDEFINED_GROUP.EXTENDED',
          'EXAMPLE_FEATUTRE_PROPERTY_SEARCH.PREDEFINED_GROUP.FULL',
        ],
      },
  ]
----

Explanation of the properties:

*	The `+columnType+` defines the type of the column. The following column types are available:
[subs=+macros]

[source, javascript]
----
  export const enum ColumnType {
    STRING = 'STRING',
    NUMBER = 'NUMBER',
    DATE = 'DATE',
    RELATIVE_DATE = 'RELATIVE_DATE',
    TRANSLATION_KEY = 'TRANSLATION_KEY',
  }
----

* The property `+id+` provides the id of the column.
* The property `+nameKey+` provides the translation string for the column header name. Furthermore, the translation needs to be added to the `+de.json+` and `+en.json+` file.
* The property `+filterable+` indicates if the column is filterable.
* The property `+sortable+` indicates if the column is sortable.
* The property `+predefinedGroupKeys+` defines in which group sets the following column is available. Furthermore, the predefinedGroups can be selected in a dropdown on top of the search results table. If you want that your searchColumn only belongs to your default column group, then only add `+FEATURE_SEARCH.PREDEFINED_GROUP.DEFAULT+`.

include::partial$remove-action.adoc[]

[#action-7]
== ACTION S7: Mapping of the items and respective translations

Here you can create a mapping of the items and their corresponding translation keys and adapt the mapping as required.

_Adapt in File:_ <feature>-search.selectors.ts
.Example:
[subs=+macros]
[source, javascript]
----
  export const selectResults = createSelector(
    ExampleFeaturePropertySearchSelectors.selectResults,
    (results): RowListGridData[] => {
      return results.map((item) => ({      
        imagePath: '',
        ...item,
        columnId1: item.columnId1
          ? `EXAMPLE_FEATUTRE_PROPERTY_SEARCH.RESULTS.COLUMNID1.${item.columnId1}`
          : '',
      }));
    }
  );
----

include::partial$remove-action.adoc[]

[#action-8]
== ACTION S8: Add translation
// TODO: Specify for what the translation is for : column headers and enums

_Adapt in File:_ `+de.json+` / `+en.json+`

Please add the missing translations

include::partial$remove-action.adoc[]
