== Configure the search criteria and parameters

:idprefix:
:idseparator: -

:adding_search_criteria_general_cookbook_url: xref:latest@guides:angular:ngrx/cookbook/adding-search-criteria/general.adoc
:adding_search_criteria_general_parameters_cookbook_url: xref:latest@guides:angular:ngrx/cookbook/adding-search-criteria/general.adoc#parameters
:adding_search_criteria_general_html_url: xref:latest@guides:angular:ngrx/cookbook/adding-search-criteria/general.adoc#html
:adding_search_criteria_general_html_examples_url: xref:latest@guides:angular:ngrx/cookbook/adding-search-criteria/general.adoc#examples-for-different-input-fields
:translation_cookbook_url: xref:latest@guides:angular:cookbook/multi-language/multi-language.adoc
:api_scheme_url: xref:latest@guides:general/api_guidelines.adoc

After generating the search page, you can add filter criteria. These criteria must be defined in the BFF's OpenAPI spec and represented in TypeScript for use in the UI. Users enter criteria via HTML input fields placed at the top of the page.

[#action-1]
=== ACTION S1: Add additional properties to search request schema

The `+Search<FeatureName>Request+` component in the OpenAPI yaml must be adapted. 

You should have a xref:getting_started/explanations.adoc#feature[`+Search<Feature>Request+`]  defined in the OpenAPI specification.
By modifying the xref:getting_started/explanations.adoc#feature[`+Search<Feature>Request+`], you can add additional parameters to your search request.

_Adapt in File:_ `+<feature>-bff.yaml+`

.Example:
[source, yml]
----
Search<Feature>Request:
      type: object
      properties:
        pageNumber: 
          type: integer
          format: int32
          default: 0
          description: 'The number of the page.'          
        pageSize:
          type: integer
          format: int32
          default: 100
          maximum: 1000
          description: 'The size of the page.'      
        id:
          type: string
        exampleProperty:
          type: string
----

Please refer to the {adding_search_criteria_general_cookbook_url}[adding search criteria general cookbook] for more information.

IMPORTANT: After updating the OpenAPI specification, execute the command *npm run apigen* to generate the corresponding TypeScript code.

include::partial$remove-action.adoc[]

[#action-2]
=== ACTION S2: Search criteria representation in zod
The criteria you added in "Action S1" now have to be added to the xref:getting_started/explanations.adoc#feature[`+<feature>SearchCriteriasSchema+`].
Assure the keys and types match the ones you defined in the OpenAPI specification.

Refer to the {adding_search_criteria_general_parameters_cookbook_url}[adding search criteria parameters cookbook] for more information.

include::partial$remove-action.adoc[]

[#action-3]
=== ACTION S3: HTML input fields for search criteria
To make the search criteria visible and usable for the user, you need to add corresponding HTML input fields to the search component's HTML file.

Please refer to the {adding_search_criteria_general_html_url}[adding search criteria html cookbook] for more information.

[#examples-for-different-input-fields]
==== Examples for different input fields
Depending on what kind of input fields you want to add, the implementation differs.
You can add different types of input fields, like `+Text+`, `+Calendar+`, `+Dropdown+`, `+MultiSelect+`, `+AutoComplete+`.
Refer to the {adding_search_criteria_general_html_examples_url}[adding search criteria examples for different input fields cookbook].

[#action-4]
=== ACTION S4: Add translations
_Adapt in File:_  `+de.json+` / `+en.json+`

Please ensure that all input field labels have the necessary translations added.

.Example
[source, json]
----
  {
    "EXAMPLE_FEATURE_SEARCH.CRITERIA.ID": "Example input field label"
  } 
----
Translations are needed for your input fields, additional labels or dropdown values.

Refer to the {translation_cookbook_url}[Multi-Language Cookbook] for more information.


---
Now you can continue with the next section xref:getting_started/search/configure-search-results.adoc[Configure search results]