=== Configure the search criteria and parameters
To configure the search results, the following actions must be taken.
// TODO: Provide explanation about: The mapping of the URL parameters must be configured. 


=== ACTION S1: Add additional properties to the <feature>-bff.yaml
__This step is only necessary if you decided to generate API-Endpoints & Components.__

* The <FeatureName>SearchRequest data structure in the BFF yaml must be adapted. 

** All the data that should be displayed in the request must be in that data structure either on top-level or in sub data structures. 

*Where this snippet can be found*: <feature>-bff.yaml.

=== ACTION S2: Please define the members for your <%= featurePropertyName %>SearchCriteriasSchema here
// TODO: Move the examples in comments from the zod library to the documentation here
// TODO: Provide an example 
*Where this snippet can be found*: <feature>-search.parameters.ts. :
[subs=+macros]
// TODO: Show that the names should have the same name as in the yaml
----
    // Here you can add an additional transform to e.g. convert to array of enum
----

*HINT*: Please remove the "ACTION" comment after solving this issue

=== ACTION S3: Please specify here your desired search criterias, link to documentation
// TODO: add info how to handle dates in p-calendar -> https://primeng.org/calendar#api.calendar.props.dateFormat
// TODO: Show that the names should have the same name as in the yaml
The input fields must be added.
*Where this snippet can be found*: <feature>-search.component.html. :
[subs=+macros]

----
 <form [formGroup]="criteriaGroup">
      <div class="grid mt-0 p-fluid">
        <div class="col-12 md:col-3">
          <span class="p-float-label">
           // PLACE YOUR INPUT FIELD HERE
          </span>
        </div>
        ....
----

* Examples for different fields
** Example for text input field
*** Remove // PLACE YOUR INPUT FIELD HERE and paste the following code

----
    <input
      id="id"
      pInputText
      type="number"
      formControlName="id"
      class="p-inputtext p-component"
      [ngModel]="vm.searchCriteria.id"
    />
    <label for="taskId">{{
      'YOUR_PRODUCT.CRITERIA.ID' | translate
    }}</label>
----

** Example for calendar input field
*** Remove // PLACE YOUR INPUT FIELD HERE and paste the following code
----
    <p-calendar
      id="endDate"
      pInputDate
      type="text"
      appendTo="body"
      formControlName="endDate"
    ></p-calendar>
    <label for="endDate">{{
      'YOUR_PRODUCT.END_DATE' | translate
    }}</label>
----

** Example for dropdown
*** Remove // PLACE YOUR INPUT FIELD HERE and paste the following code
----
 <p-multiSelect [options]="dropdownOptions" formControlName="selectedOptions" optionLabel="name" placeholder="Select Options"></p-multiSelect>
----
** Directive *ocxAdvanced
** The directive *ocxAdvanced indicates if a field belongs to the basic or the advanced mode. The mode can be toggled via a button in the search header.
The directive *ocxAdvanced will be added to the div.

----
 <div *ocxAdvanced class="col-12 md:col-3">
          <span class="p-float-label">
          // INSERT your input field HERE
          </span>
  </div>
----
The information if a field belongs to the basic or advanced view will be added to the <%= featureClassName %>SearchViewModel and the information is saved in the member 'viewMode'

*HINT*: Please remove the "ACTION" comment after solving this issue

=== ACTION S4: ADD TRANSLATION for your input fields
// TODO: Specify for what the translation will be added

*Where this snippet can be found*: de.json / en.json  :
Please add the missing translations

