= OneCX App Generator

The OneCX App Generator is a powerful tool designed to streamline the development of applications within the OneCX framework. It automates the creation of essential components, ensuring consistency and adherence to best practices.

== Prerequisites
Ensure your development environment is set up correctly before using the OneCX App Generator:

The following tools must be installed and versions verified:

** *npm* version should be >= 10.2.4
** *node* version should be 20.11.0
** *nx* - Local: v19.6.4
** *nx* - Global: v20.0.6

.Check versions
[source,bash]
----
node --version
npm --version
nx --version
----

.Install the Nx CLI globally
[source,bash]
----
npm install -g nx@latest
----

In case of issues during *Nx* installation, try the following steps:

.Nx CLI installation issue resolution
[source,bash]
----
rm -rf node_modules
npm cache verify
npm install -g @nrwl/cli
npm install
----


== Generable Components

The following application types and components can be generated using the OneCX App Generator:

* OneCX App
** Feature Module
*** Search Page
*** Details Page
*** Create/Update Dialog
*** Delete Dialog
*** Simple NgRx Page
** Pre Commit Validation
