ifdef::env-site[]
include::partial$_attributes.adoc[]
endif::[]
:page-hide-prev:
:imagesdir: ../images

= OneCX App Generator

The OneCX App Generator is a powerful tool that simplifies the development of UI applications within the OneCX framework. It automates the creation of key UI components, ensuring consistency and adherence to best practices.

Nevertheless, essential parts still need to be created or modified manually by the user.

== Prerequisites
Make sure your development environment is set up correctly before using the OneCX App Generator. +
The following tools must be installed and versions verified:

** *npm* version should be >= 10.2.4
** *node* version should be 20.11.0
** *nx* - Local: v19.6.4
** *nx* - Global: v20.0.6

.Check versions
[source,bash]
----
node --version
npm --version
nx --version
----

.Install the Nx CLI globally
[source,bash]
----
npm install -g nx@latest
----

In case of issues during *Nx* installation, try the following steps:

.Nx CLI installation issue resolution
[source,bash]
----
rm -rf node_modules
npm cache verify
npm install -g @nrwl/cli
npm install
----


== Get the Generator

. Clone the *onecx-nx-plugins* repository into a folder on the local machine/inside WSL2
+
[source,bash]
----
git clone https://github.com/onecx/onecx-nx-plugins.git
----

. Navigate into the cloned repository and install the dependencies
+
[source,bash]
----
cd onecx-nx-plugins
npm install
----

. Build the OneCX App Generator
+
[source,bash]
----
npm run build
----


== Generation Process

The generator offers a range of commands to gradually create various UI components such as applications, function modules, and pages. During the generation of some parts, you will be prompted to specify parameters that determine the structure and naming of the generated components. Occasionally, code adjustments will be necessary to implement business requirements. +
Make the adjustments carefully and in accordance with the specifications and naming conventions of your project to ensure consistency and maintainability of the codebase.

Here is an overview of the application parts that can be generated using the OneCX App Generator:

* xref:generator/create-app.adoc[OneCX UI App]
** xref:generator/create-feature.adoc[Feature Module]
*** xref:generator/create-search.adoc[Search Page]
*** Details Page
*** Create/Update Dialog
*** Delete Dialog
*** Simple NgRx Page
** Pre Commit Validation
