== Add the data to the details page

:idprefix:
:idseparator: -

:adding_details_cookbook_url: xref:latest@guides:angular:ngrx/cookbook/adding-details-page/details-page.adoc
:adding_details_tab_cookbook_url: xref:latest@guides:angular:ngrx/cookbook/adding-details-page/details-page.adoc#tab
:adding_header_actions_cookbook_url: xref:latest@guides:angular:ngrx/cookbook/adding-header-actions/actions.adoc

On details page you can display the data in the the header, by defining the label and value pairs. Below the header a `tabView` component with desired number tabs can be displayed. The content of each tab can be defined in separate components.

[#action-1]
=== ACTION D1: Define values to be shown in the header

The details page will display the header with the title and subtitle. You can modify those values in xref:getting_started/explanations.adoc#feature[`+<feature>-details.component+`]. In order to customize the header, extend the `headerLabels` property of type `ObjectDetailItem`.  Please, reference the {adding_details_cookbook_url}[cookbook] for more information.

_Remove "ACTION D1" comment after working on this task._


=== ACTION D2: Update header actions

You can add desirable actions to your details page. And it will be possible to trigger them from designated area on the top right corner of the page. 
For the details page, the generator creates 2 actions for the header by default. Consider adding custom actions to be available in the header via `headerActions$` property. 
Please refer to the {adding_header_actions_cookbook_url}["Adding header actions" cookbook] for details.

=== ACTION D3: Define tab component

For the tab component you should implement a function handling tab change in xref:getting_started/explanations.adoc#feature[`+<feature>-details.component+`] and you need to define `+<p-tabView></p-tabView>+` in the html. Check the {adding_details_tab_cookbook_url}[cookbook] for examples.


