=== Create a new OneCX app 
The fastest way to create a new OneCX app is to use the OneCX generator. Some projects have their own generator based on the OneCX generator. It should be clarified before starting if this is the case for the project the app is generated for. 

The generator supports two flavors of projects angular with and without NgRx. It is recommended to use the NgRx flavor because it leads to better structured projects and currently the support in the generator is better for the NgRx flavor.  

*****
To run the generator, execute the following two commands: 

----
npx <namespaceOfTheGenerator>/create-workspace <flavor> <nameOfTheProduct> 
npm install
----

*Placeholder*: 

* _<namespaceOfTheGenerator>_: For the OneCX generator use `+@onecx+`. For a project specific generator, ask for the namespace of the generators. 

* _<flavor>_: `+ngrx+` or `+angular+`

* _<nameOfTheProduct>_: The name of the product to create e.g., `+theme-mgmt+`
*****

After running the generator take the following actions: 
[start=1]
. xref:getting_started/basicOneCXApp/checkForFurtherActions.adoc[Check for further actions]
. xref:getting_started/basicOneCXApp/commitTheChanges.adoc[Commit the changes]

Next you might want to generate a feature as this is a preqrequisite to generate a search / details page and more.