=== Create a new OneCX app 
The fastest way to create a new OneCX app is to use the OneCX generator.
include::partial$generatorCheck.adoc[]

The generator supports three flavors of projects: angular, with and without NgRx. It is recommended to use the NgRx flavor because it leads to better structured projects and currently the support in the generator is better for the NgRx flavor. If you plan not to use any onecx-services and build a standalone app with the components of OneCX, please use `+ngrx-standalone+`.

*****
To run the generator, execute the following commands: 

// TODO: Is npm install needed?
----
npx <namespaceOfTheGenerator>/create-workspace <flavor> <nameOfTheProduct> 
npm install
----

include::partial$namespaceOfTheGeneratorItem.adoc[]

* _<flavor>_: `+ngrx+`, `+ngrx-standalone+` or `+angular+`.

* _<nameOfTheProduct>_: The name of the product to create e.g., `+theme-mgmt+`.
*****

After running the generator take the following actions: 
[start=1]
. xref:getting_started/basicOneCXApp/checkForFurtherActions.adoc[Check for further actions]
. xref:getting_started/basicOneCXApp/commitTheChanges.adoc[Commit the changes]

Next you might want to generate a feature as this is a preqrequisite to generate a search / details page and more.