=== Create Create/Update Dialogs

:idprefix:
:idseparator: -

The fastest way to create a create and update dialogs in a feature module is to use the OneCX generator.
include::partial$generator-check.adoc[]

******
To run the generator, execute the following command: 

----
nx generate <namespaceOfTheGenerator>/nx-plugin:create-update <nameOfTheFeature> [--standalone]
----

include::partial$generator-namespace-item.adoc[]

* _<nameOfTheFeature>_: The name the feature the create-update dialog should be created in e.g., theme.

TIP: Next, the CLI will ask you whether you want to customize names for the generation.
When answering yes, the next few questions will ask you about names for the API.
This can be useful if you want to adapt to a legacy API. 
When modifying names, assure that you use the same custom names for all generated components of the feature (search, details, create-update, delete) for the data object name, and the api service name as these ones are shared.

*Options*:

* --standalone: if you want to develop an application that does not depend on onecx-services

******

After running the generator, the following actions must be taken: 


[start=1]
. xref:getting_started/create-update/extend-form-fields.adoc[Extend schema and form fields]
. xref:getting_started/create-update/commit-changes.adoc[Commit the changes]
