=== Create a details page
The fastest way to create a new details page in a feature module is to use the OneCX generator. Some projects have their own generator based on the OneCX generator. It should be clarified before starting if this is the case for the project the app is generated for. 

To run the generator, execute the following command: 

----
nx generate <namespaceOfTheGenerator>/nx-plugin:details <nameOfTheFeature>: 
----

Replace the placeholders with the following values: 

* _<namespaceOfTheGenerator>_: For the OneCX generator use @onecx. For a project specific generator, ask for the namespace of the generators. 

* _<nameOfTheFeature>_: The name the feature the details page should be created in e.g., theme 

After running the generator, the following actions must be taken: 

[start=1]
. xref:getting_started/details/addNotDynamicallyLoadedDataToResponse.adoc[Add not dynamically loaded data to response]
. xref:getting_started/details/addCoreDataToDetailsPageHeader.adoc[Add core data to details page header]
. xref:getting_started/details/addRestOfTheDataToBody.adoc[Add the rest of the data to the body]
. xref:getting_started/details/checkForFurtherActions.adoc[Check for further actions]
. xref:getting_started/details/commitTheChanges.adoc[Commit the changes]