=== Create a search page
The fastest way to create a new search page in a feature module is to use the OneCX generator.
include::partial$generatorCheck.adoc[]

******
To run the generator, execute the following command: 
----
nx generate <namespaceOfTheGenerator>/nx-plugin:search <nameOfTheFeature> [--standalone]
----

include::partial$nameOfTheGeneratorItem.adoc[]

* _<nameOfTheFeature>_: The name of the feature the search page should be created in, e.g., theme 

TIP: Next, the CLI will ask you whether you want to customize names for the generation.
When answering yes, the next few questions will ask you about names for the API.
This can be useful if you want to adapt to a legacy API.
When modifying names, assure that you use the same custom names for all generated components of the feature (search, details, create-update, delete) for the data object name, and the api service name as these are shared.

*Options*:

* --standalone: if you want to develop an application that does not depend on onecx-services.

******

After running the generator, the following actions must be taken: 

[start=1]
. xref:getting_started/search/configureSearchCriteria.adoc[Configure search criteria]
. xref:getting_started/search/configureSearchResults.adoc[Configure search results]
. xref:getting_started/search/configureResultDiagram.adoc[Configure result diagram]
. xref:getting_started/search/updateHeaderActions.adoc[Update Header Actions]
. xref:getting_started/search/updatePermissions.adoc[Update permissions]
. xref:getting_started/search/checkForFurtherActions.adoc[Check for further actions]
. xref:getting_started/search/commitTheChanges.adoc[Commit the changes]
