=== Create Delete Dialog

:portal_dialog_service_url: xref:latest@guides:angular:cookbook/service/portal-dialog-service/index.adoc
:idprefix:
:idseparator: -

The fastest way to create a delete dialog in a feature module is to use the OneCX generator.
include::partial$generator-check.adoc[]

******
To run the generator, execute the following command: 

----
nx generate <namespaceOfTheGenerator>/nx-plugin:delete <feature> [--standalone]
----

include::partial$generator-namespace-item.adoc[]

* <feature> should be replaced as described xref:getting_started/explanations.adoc#feature[here].

TIP: Next, the CLI will ask you whether you want to customize names for the generation.
When answering yes, the next few questions will ask you about names for the API.
This can be useful if you want to adapt to a legacy API. 
When modifying names, assure that you use the same custom names for all generated components of the feature (search, details, create-update, delete) for the data object name, and the api service name as these ones are shared.

*Options*:

* --standalone: if you want to develop an application that does not depend on onecx-services.

******

[start=1]
. xref:getting_started/delete/commit-changes.adoc[Commit the changes]

NOTE: To modify the behavior of the dialogs, please refer to {portal_dialog_service_url}[PortalDialogService docs].
