== Define input fields


:header_actions_url: xref:getting_started/search/update-header-actions.adoc
:adding_create_update_dialog_cookbook_url: xref:latest@guides:angular:ngrx/cookbook/create-or-update-dialog/create-update.adoc#bff
:adding_create_update_html_cookbook_url: xref:latest@guides:angular:ngrx/cookbook/create-or-update-dialog/create-update.adoc#html
:adding_create_update_parameters_cookbook_url: xref:latest@guides:angular:ngrx/cookbook/create-or-update-dialog/create-update.adoc#fields
:adding_create_update_header_action_cookbook_url: xref:latest@guides:angular:ngrx/cookbook/create-or-update-dialog/create-update.adoc#action

:idprefix:
:idseparator: -

In order to implement a dialog for creating/updating an entity, first you should provide OpenAPI specification of BFF endpoint, which performs desired action in the database. You also need to add typescript representation of the input fields into typescript component. Next you need to add a header action button, which would invoke a pop-up dialog. The HTML input fields can be placed inside the dialog. The values from the input fields would be passed to typescript component and then to bff endpoint.


[#action-1]
=== ACTION C1: OpenAPI specification of the objects in BFF endpoint
Each input parameter needs to be added to creat/update requests in `+<feature>-bff.yaml+` file as described in the section {adding_create_update_dialog_cookbook_url}[ "OpenAPI specification of the objects in BFF endpoint" of the cookbook].

Run the command *npm run apigen* after adapting the OpenAPI to transform the changes into typescript code.

_Remove "ACTION C1" comment after working on this task._

[#action-2]
=== ACTION C2: HTML input fields for create/update
For each create/update property adapt `+<feature>-create-update.component.html+` file as described in the section {adding_create_update_html_cookbook_url}[ "HTML input fields for create/update" of the cookbook].

_Remove "ACTION C2" comment after working on this task._

[#action-3]
=== ACTION C3: Add form fields to typescript component
For each create/update property adapt `+<feature>-create-update.component.html+` file as described in the section {adding_create_update_parameters_cookbook_url}[ " Add form fields to typescript component" of the cookbook].

_Remove "ACTION C3" comment after working on this task._

[#action-4]
=== ACTION C4 Add header action for "create" button

After you add a header action as described in {header_actions_url}["Update header actions" section], checkout the example for the effect triggering pop-up dialog in the section {adding_create_update_header_action_cookbook_url}[ "Add header action for "create" button" of the cookbook].
