#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

BLACKLIST_FILE=${BLACKLIST_FILE:-"$HOME/blacklist.txt"}
PLUGIN_PATH="scripts/detect-secrets-plugin.ts"

if [ ! -f "$BLACKLIST_FILE" ]; then
  echo "Blacklist file not found. Please create a new blacklist.txt in your home directory."
  exit 1
fi

CHANGED_FILES=$(git diff --name-only HEAD)

if [ -z "$CHANGED_FILES" ]; then
  echo "No changed files detected. Skipping detect-secrets check."
  exit 0
fi

for file in $CHANGED_FILES; do
  if [ -f "$file" ]; then
    npx ts-node "$PLUGIN_PATH" "$file" "$BLACKLIST_FILE"
    if [ $? -ne 0 ]; then
      echo "Secret words detected in $file."
      exit 1
    fi
  fi
done

echo "No secrets found."
